[tcp]
device     = "lo"
snaplen    = 300
ports      = [6379]
timeout_ms = 1000
# filter  = "tcp port 6379"

[input]
type = "tcp_redis_size"  # only "tcp_redis_size" in v0.1
commands = ["SET"]
interval = 60

[output]
format = "{size}\t{time}\t{src}\t{key}"
