[pcap]
device     = "lo"
snaplen    = 300
ports      = [6379]
timeout_ms = 1000
# filter  = "tcp port 6379"

[input]
type = "redis_tcp_set_size"  # "redis_tcp_set_size" only
interval = 60

[output]
format = "{size}\t{time}\t{src}\t{key}"
